### ISSUE TITLE
hadoop: command not found when mesos.hdfs.native-hadoop-binaries == false

### ISSUE THREAD

**Issue by ryane** [mesosphere/hdfs#155] opened 2015-07-20 20:46 UTC
I am trying to run the hdfs framework without having native hadoop binaries in place. My mesos-site.xml is set with the following:

```xml
  <property>
    <name>mesos.hdfs.native-hadoop-binaries</name>
    <description>Mark true if you have hadoop pre-installed on your host machines (otherwise it will be distributed by the scheduler)</description>
    <value>false</value>
  </property>
```

However, when the framework is starting, I see the following in the logs:

```
I0720 19:59:40.833745 11518 fetcher.cpp:214] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/hdfs/artifacts/dcos/0.1.1/hdfs-mesos-0.1.1.tgz'
I0720 19:59:40.833884 11518 fetcher.cpp:125] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/hdfs/artifacts/dcos/0.1.1/hdfs-mesos-0.1.1.tgz' with os::net
I0720 19:59:40.833892 11518 fetcher.cpp:135] Downloading 'https://s3.amazonaws.com/downloads.mesosphere.io/hdfs/artifacts/dcos/0.1.1/hdfs-mesos-0.1.1.tgz' to '/tmp/mesos/slaves/20150720-194404-202637322-15050-13331-S0/frameworks/20150720-194404-202637322-15050-13331-0000/executors/hdfs.db7da3b8-2f19-11e5-bd22-e200e27485f9/runs/108ae53c-3681-466e-9cff-db5496c53451/hdfs-mesos-0.1.1.tgz'
I0720 19:59:49.414286 11518 fetcher.cpp:78] Extracted resource '/tmp/mesos/slaves/20150720-194404-202637322-15050-13331-S0/frameworks/20150720-194404-202637322-15050-13331-0000/executors/hdfs.db7da3b8-2f19-11e5-bd22-e200e27485f9/runs/108ae53c-3681-466e-9cff-db5496c53451/hdfs-mesos-0.1.1.tgz' into '/tmp/mesos/slaves/20150720-194404-202637322-15050-13331-S0/frameworks/20150720-194404-202637322-15050-13331-0000/executors/hdfs.db7da3b8-2f19-11e5-bd22-e200e27485f9/runs/108ae53c-3681-466e-9cff-db5496c53451'
I0720 19:59:49.523723 11516 exec.cpp:132] Version: 0.22.1
I0720 19:59:49.526216 11526 exec.cpp:206] Executor registered on slave 20150720-194404-202637322-15050-13331-S0
sh: hadoop: command not found
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0720 19:59:49.648200 11541 main.cpp:99] Ignoring failure as health check still in grace period

...

I0720 19:59:50.188393 11566 detector.cpp:452] A new leading master (UPID=master@10.0.20.12:15050) is detected
I0720 19:59:50.188437 11566 sched.cpp:254] New master detected at master@10.0.20.12:15050
I0720 19:59:50.188561 11566 sched.cpp:264] No credentials provided. Attempting to register without authentication
I0720 19:59:50.191442 11566 sched.cpp:448] Framework registered with 20150720-194404-202637322-15050-13331-0002
sh: hadoop: command not found
I0720 20:00:49.725492 11544 main.cpp:99] Ignoring failure as health check still in grace period
sh: hadoop: command not found
I0720 20:01:49.777657 11541 main.cpp:99] Ignoring failure as health check still in grace period
sh: hadoop: command not found
```

Is there anything else I need to do in order to be able to run the framework without having the hadoop binaries pre-installed?

**Comment by elingg** [comment] 2015-07-20 22:00
hi @ryane, can you remove your health check in your marathon.json and retry? Yes, this should work without problems by following the instructions here on github.

**Comment by elingg** [comment] 2015-07-20 22:05
As another note here, the health check will fail for sometime until the binaries are distributed on the slaves. That is ok, but you may want to extend your health check time period...

**Comment by ryane** [comment] 2015-07-23 15:11
It turns out the problem is more with dcos hdfs package installer. I created a new issue at https://github.com/mesosphere/dcos-hdfs/issues/5.

**Comment by elingg** [comment] 2015-07-23 17:21
Hello @ryane, You are correct that this should be dynamic and we should be using environment variables for configuration and this is part of our roadmap. Meanwhile, I will update the readme to let people know that they can set their configurations at compile time (in that case, the executor will have the correct configuration files bundled).

**Comment by elingg** [comment] 2015-07-23 22:17
See my PR here, https://github.com/mesosphere/hdfs/pull/160

**Comment by elingg** [comment] 2015-07-23 22:20
Closing this issue as duplicate of https://github.com/mesosphere/universe/issues/185. Please reopen if you think it warrants a separate issue.

**Closed** 2015-09-15 06:13 UTC
