### ISSUE TITLE
Configuration required to potentially have datanode task on namenode or journal node.

### ISSUE THREAD

**Issue by nigoel** [mesosphere/hdfs#178] opened 2015-08-26 05:56 UTC
For a small mesos cluster at times it is required to have datanodes be on the same slaves where we have namenode or journal nodes. This option can be by default turned off, but must be configurable.

**Comment by T0aD** [comment] 2015-08-28 16:07
I agree, we have a cluster of 5 boxes, and unfortunately only 2 are used as DataNodes.

**Comment by elingg** [comment] 2015-09-28 21:20
This patch was merged so the issue is now closed. Thanks @nigoel

**Closed by elingg** 2015-09-28 21:20 UTC
